version: '3'

services:
  sinatra:
    # tty, stdin_open は binding.pry のために必要
    tty: true
    stdin_open: true
    build:
      # Dockerfile の app のコピーのために必要なパス指定
      context: ../
      # context のパスから見た Dockerfile の場所
      dockerfile: docker/Dockerfile
    volumes:
      - ~/Dev/sinatra/app:/app
    ports:
      - "9292:9292"